### ISSUE TITLE
Variable names seem inconsistent

### ISSUE THREAD

**Issue by legacy370** [intuit/oauth-rubyclient#1]
One one line, it declares a variable named client:
client = IntuitOAuth::Client.new('client_id', 'client_secret', 'redirectUrl', 'environment')

Then, a few lines down, it uses a variable named oauth_client:
authorizationCodeUrl = oauth_client.code.get_auth_uri(scopes)
Which gives an error: undefined local variable or method `oauth_client' for #<QuickbooksController:0x0000558edb726b08>.

A complete, working example would be extremely helpful.

**Comment by hlu2** [comment]
@legacy370 
Thanks! It is a typo, I have changed the ReadMe doc!
