### ISSUE TITLE
QUESTION: after authentication steps, how to pull information from the accounts?

### ISSUE THREAD

**Issue by designium** [intuit/oauth-rubyclient#13]
Hi,

Happy thanksgiving.

I'm currently using Rails 6.0.1.

After obtaining the user's uid, token, refresh_token, realm_id, how can I pull invoices information from that point and beyond? 

The current gem allows us to validate the user and obtain those credentials but I don't know how to continue to do queries via the ruby gem. 

Any thoughts of next steps?

**Comment by hlu2** [comment]
Hi, @designium This is only a gem for OAuth 2.0 authentication. If you need to make any API calls, please use https://github.com/ruckus/quickbooks-ruby this gem.
