### ISSUE TITLE
Changes to identity signature keys

### ISSUE THREAD

**Issue by Garrett-Rewind** [intuit/oauth-rubyclient#19]
Hello,

In this Intuit blog post [https://blogs.intuit.com/2023/09/05/changes-to-identity-signature-keys-that-may-impact-your-application/](https://blogs.intuit.com/2023/09/05/changes-to-identity-signature-keys-that-may-impact-your-application/ ) its state that March 1st 2024 the response array from [oauth.platform.intuit.com/op/v1/jwks](oauth.platform.intuit.com/op/v1/jwks) will now return multiple keys.

Are there plans to update this repo to address the change?

Specifically, I believe these lines will be faulty after March 1, 2024:
[](https://github.com/intuit/oauth-rubyclient/blob/abd3e84e9fe194464e401a82ef3e32b414891d54/lib/intuit-oauth/flow/openid.rb#L83-L90)](https://github.com/intuit/oauth-rubyclient/blob/abd3e84e9fe194464e401a82ef3e32b414891d54/lib/intuit-oauth/flow/openid.rb#L83-L90)

**Comment by sethu-intuitdev** [comment]
@Garrett-Rewind thank you for your message. Yes, that's correct and we aware of this faulty code block that is not looping through all the available keys. We already working on the change & will create the PR soon. Would you be able to help with the testing?

**Comment by Garrett-Rewind** [comment]
Hi @sethu-intuitdev,

For sure, I'm happy to help,  I can test with our app once the PR is up.

Do you happen to have an expected date for when the changes will be ready?

**Comment by sethu-intuitdev** [comment]
@Garrett-Rewind thank you so much! I have raised the PR with required changes to loop through the keys. https://github.com/intuit/oauth-rubyclient/pull/20 - can you help testing and share feedback?

**Comment by Garrett-Rewind** [comment]
@sethu-intuitdev 

I cloned your repo with changes and setup our app locally with the changes.  Ran though our auth flow modifying and mocking the response from `IntuitOAuth::Transport.request(...)`.  Checked four key scenarios:

1. Single Key with match present. PASS - authorized as expected.
2. Multiple keys returned with match present.  PASS - authorized as expected.
3. Single key returned no match present. PASS - did not authorize.
4. Multiple keys returned with no match present.  PASS - did not authorize.

Appears everything is working as expected for us with your changes.

**Comment by sethu-intuitdev** [comment]
Appreciate your willingness and help validating the changes @Garrett-Rewind . I will go ahead and merge the changes. thanks once again

**Comment by Garrett-Rewind** [comment]
Hello @sethu-intuitdev ,

I see that your changes have been merged however the gem version was never increased.  Are you going to increase the gem version and publish to RubyGems so that these changes can be picked up by bundler?

**Comment by sethu-intuitdev** [comment]
@Garrett-Rewind - was working to resolve permission issues and hence the delay. Increased the gem version and published the latest version to RubyGems. https://rubygems.org/gems/intuit-oauth/versions/1.0.3

**Comment by Garrett-Rewind** [comment]
Thank you @sethu-intuitdev ! We've integrated and deployed these changes; I'll close issue out.
