### ISSUE TITLE
Remove unused json_web_token dependency

### ISSUE THREAD

**Issue by bertiecroll** [intuit/oauth-rubyclient#2]
Hi, thanks for providing the helpful library.

I may be mistaken, however I believe the json_web_token gem included as a dependency is currently unused. This gem has an alias of 'JWT' which conflicts with another gem required in our app.

The json_web_token provides an option to add an environment variable to exclude this alias, however if this gem is not being used by oauth-rubyclient can the gem be removed from being a dependency instead?

I'd be happy to submit a short PR if needed.
Many thanks

**Comment by hlu2** [comment]
@bertiecroll  Thanks for pointing out. Please submit a PR and I shall approve it soon.

Thanks
Hao

**Comment by shepmaster** [comment]
Ping @hlu2; there is a PR available.

**Comment by hlu2** [comment]
merged. Thanks!
