### ISSUE TITLE
Relax the `json` dependency to also allow `1.8.x`?

### ISSUE THREAD

**Issue by serixscorpio** [intuit/oauth-rubyclient#9]
Hi thanks for providing this gem. very helpful!

I was wondering if there were specific reasons the `json` dependency is set at [`~> 2.1`](https://github.com/intuit/oauth-rubyclient/blob/14aeaeb5e63b8c16cb5c9886da43c96526eb9ad8/intuit-oauth.gemspec#L8)?

Would there be any adverse effect if the dependency is relaxed to also allow `1.8.x`?  Thanks!

**Comment by elainemckinley** [comment]
I'm also running into this. I think relaxing the json dependency makes sense, it looks like the only breaking change with `json (2.0.0)` was dropping support for old ruby versions: https://github.com/flori/json/blob/master/CHANGES.md#2015-09-11-200

**Comment by hlu2** [comment]
I think it makes sense. I will relax the json dependency.

**Comment by elainemckinley** [comment]
@hlu2 If it's helpful, I just opened a PR for this change. Thanks also for the quick reply!

**Comment by caseyrollins** [comment]
Hi @hlu2! Would it be possible to get the related PR merged? It would allow our organization to use this gem. 🙂

**Comment by hlu2** [comment]
@caseyrollins I will review the pull request and make a new gem tomorrow~

**Comment by hlu2** [comment]
@caseyrollins It is done. Try it again and let me know if everything works fine.
